use super::StopArgs;
use colored::Colorize;
use doubleagent_core::{Config, ProcessManager};
use std::fs;
use std::path::Path;

/// Env file name for service URLs
const ENV_FILE: &str = ".doubleagent.env";

pub async fn run(args: StopArgs) -> anyhow::Result<()> {
    let config = Config::load()?;
    let mut manager = ProcessManager::load(&config.state_file)?;

    let services: Vec<String> = if args.services.is_empty() {
        manager.running_services()
    } else {
        args.services
    };

    if services.is_empty() {
        println!("No services running");
        return Ok(());
    }

    for service_name in &services {
        if !manager.is_running(service_name) {
            println!("{} {} is not running", "⚠".yellow(), service_name);
            continue;
        }

        print!("{} Stopping {}...", "■".red(), service_name);
        manager.stop(service_name).await?;
        println!(" {}", "✓".green());
    }

    manager.save(&config.state_file)?;

    // Clean up .doubleagent.env if no services are running
    if manager.running_services().is_empty() {
        cleanup_env_file();
    } else {
        // Update .doubleagent.env with remaining services
        update_env_file(&manager);
    }

    Ok(())
}

/// Remove the .doubleagent.env file
fn cleanup_env_file() {
    let env_path = Path::new(ENV_FILE);
    if env_path.exists() {
        if let Err(e) = fs::remove_file(env_path) {
            eprintln!("{} Failed to remove {}: {}", "⚠".yellow(), ENV_FILE, e);
        } else {
            println!("{} Removed {}", "✓".green(), ENV_FILE);
        }
    }
}

/// Update .doubleagent.env with remaining running services
fn update_env_file(manager: &ProcessManager) {
    let services = manager.running_services();
    if services.is_empty() {
        cleanup_env_file();
        return;
    }

    let mut content = String::from("# Generated by doubleagent - do not edit\n");
    content.push_str("# Load with: source .doubleagent.env (bash) or use dotenv library\n\n");

    for name in &services {
        if let Some(info) = manager.get_info(name) {
            let env_name = format!("DOUBLEAGENT_{}_URL", name.to_uppercase().replace('-', "_"));
            content.push_str(&format!("{}=http://localhost:{}\n", env_name, info.port));
        }
    }

    if let Err(e) = fs::write(ENV_FILE, &content) {
        eprintln!("{} Failed to update {}: {}", "⚠".yellow(), ENV_FILE, e);
    } else {
        println!("{} Updated {}", "✓".green(), ENV_FILE);
    }
}
